### ISSUE TITLE
Someone please provide some example usage

### ISSUE THREAD

**Issue by ramesh-tr** [victormacedo/Landlord#1]
I could not make it work on a Laravel 5.3 installation. Can someone provide some example usage?

Also, the tests added as part of this package is confusing.

**Comment by victormacedo** [comment]
@ramesh-tr sorry for the late response.

The original package propose the multi-tenancy with a column at every table that references the tenant id. With my improvement (motivated by a project at my current job), this package will use the polymorphic relations from Laravel-Eloquent to associate tables and tenants.

During install, at config file you will need tell to TenantManager which tentant relation must be considered: the original (_\HipsterJazzbo\Landlord\TenantManager::BELONGS_TO_TENANT_TYPE_TO_ONE_) or polymorphic (_\HipsterJazzbo\Landlord\TenantManager::BELONGS_TO_TENANT_TYPE_TO_MANY_). If polymorphic, _default_morph_relation.tenant_model_ and _default_morph_relation.tenant_relations_model_ must be informed.

No test was added after my fork from original package, sorry about that.

If you find an issue, or have a better way to do something, feel free to open an issue or a pull request.
